const User = require("./user.js");
const Muttering = require("./muttering.js");

const create_date = Date.now();

const muttering = new Muttering(1, new User(1, 'Alice'), 'I love the weather today.', create_date);

test("ID is correct", () => {
    expect(muttering.id).toBe(1);
});

test("Content is correct", () => {
    expect(muttering.content).toBe('I love the weather today.');
});

test("User property is instance of User", () => {
    expect(muttering.user).toBeInstanceOf(User);
});

test("Create date property is set correctly", () => {
    expect(muttering.create_date).toBe(create_date);
})

test("Create date property is autogenerated correctly", () => {
    new_muttering = new Muttering(1, new User(1, 'Alice'), 'I love the weather today.', create_date);
    expect(new_muttering.create_date).toEqual(expect.any(Number));
})
